version: '3.9'
services:
  api:
    build: 
    ports:
      - "3000:3000"
    environment:
      - PORT=3000

  mongo:
    image: mongo
    environment:
       MONGO_INITDB_ROOT_USERNAME: abel
       MONGO_INITDB_ROOT_PASSWORD: TU01-BE213-0634/2019